# -*- coding: utf-8 -*-
"""Streamlit_Rosas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irduVEfM0fdHTJwYovYiBFRwd7bd7cqX
"""

service_account_mail = 'service-acc@fair-bearing-434109-c8.iam.gserviceaccount.com'

!pip install st-gsheets-connection

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_rosas.py
# import streamlit as st
# from streamlit_gsheets import GSheetsConnection
# 
# # Create a connection object.
# conn = st.connection("gsheets", type=GSheetsConnection)
# 
# df = conn.read()

!streamlit run /content/streamlit_rosas.py &>/content/logs.txt &

!wget -q -O - ipv4.icanhazip.com

!npx localtunnel --port 8501

